development:
  adapter: async

test:
  adapter: test

# Production configuration for Heroku
production:
  adapter: solid_cable
  connects_to:
    database:
      writing: primary
  polling_interval: 0.1.seconds
  message_retention: 1.day
